title: "Cuaderno"
author: "SM"
description: ""
url: "http://sonomayrit.xyz"
baseurl: ""
lang: "es"

excerpt_separator: <!--more-->

plugins: [jekyll-paginate]

markdown: kramdown
kramdown:
  header_offset: 1

permalink: /:year/:month/:day/:title/
paginate_pathds: /:num/
paginate: 5

exclude: [notes.md, _posts/2020-01-01-template.md]

collections:
  projects:
    output: true